version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/go-api/Dockerfile

    environment:
      - GRPC_ENDPOINT=dns:///worker:9090
    ports:
      - "8080:8080"

  worker:
    build:
      context: .
      dockerfile: ./docker/ts-worker/Dockerfile
    ports:
      - "9090:9090"
