name: API tests
on: [push]
jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
    defaults:
      run:
        working-directory: ./go-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - run: go get .
      - run: go build -v .
      - run: go test -v ./booklight
