name: API tests
on: [push]
jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go-api
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - run: go mod tidy
      - run: go build -v .
      - run: go test -v ./booklight
